# Generated by Django 5.2.1 on 2025-06-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clipath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clipath/')),
                ('alternative', models.TextField(default='CSS predesigned clip-path with code.', help_text='Description about the uploaded image.')),
                ('category', models.CharField(choices=[('header', 'Header'), ('footer', 'Footer')], max_length=6)),
                ('sender', models.CharField(help_text='Sender Email Address or GitHub.', max_length=60)),
                ('active', models.BooleanField(default=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
