# Generated by Django 5.2.1 on 2025-06-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipath',
            name='code',
            field=models.TextField(default="Couldn't Copy the Code.", help_text='Uploaded Image clip-path Code.'),
        ),
    ]
